name: CI
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00, on day 1 of the month
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: juliangruber/read-file-action@v1
        id: addresses
        with:
          path: ./addresses.txt
          trim: true
      - uses: filecoin-station/w3name-update-action@v0
        with:
          value: ${{ steps.addresses.outputs.content }}
          private-key: ${{ secrets.W3NAME_PRIVATE_KEY }}
          revision: ${{ secrets.W3NAME_REVISION }}
      - if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "alerts",
              "text": "Republishing contract addresses failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Republishing contract addresses failed>*"
                  }
                }
              ]
            }
